{% set name = "grpcio-health-checking" %}
{% set version = "1.33.2" %}

# TODO: this upstream pin appears to not be updated w/r/t to code generation version
{% set min_protobuf = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35f8bce59f5e3b16ac524f954597dc54195e3277b1d600c96f54fc64780ebdf6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - grpcio >={{ version }}
    - protobuf >={{ min_protobuf }}
    - python >=3.5

test:
  source_files:
    - grpc_version.py
  imports:
    - grpc_health
    - grpc_health.v1.health
  commands:
    - pip check
  requires:
    - pip
    # do import tests with the minimum to assure it hasn't changed
    - protobuf =={{ min_protobuf }}

about:
  home: https://grpc.io
  summary: Standard Health Checking Service for gRPC
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/grpc/grpc/tree/master/src/python/grpcio_health_checking

extra:
  recipe-maintainers:
    - bollwyvl
